DATABASE_NAME   	= "generation_output.db"

WIDTH  				= 600
HEIGHT 				= 600

POPULATION_SIZE 	= 20
TARGET_COUNT    	= 20

MUTATION_RATE   	= .05

MEMBER_RADIUS   	= 10
TARGET_RADIUS       = 5

DEFAULT_BRAIN_SHAPE = [ 4, 4, 2 ]
DEFAULT_ENERGY      = 1000